### ISSUE TITLE
Scratch pad opened from right

### ISSUE THREAD

**Issue by kaiphat** [FraserLee/ScratchPad#1]
I don't have any configurations.
![image](https://user-images.githubusercontent.com/53742299/161218636-a321ebab-3a8e-4b75-8434-82d73b705593.png)

**Comment by Iliyapunko** [comment]
Terminal: kitty.
Nvim: NVIM v0.7.0-dev

**Comment by FraserLee** [comment]
That's weird. Any chance you could send me your .vimrc so I could take a look at what's happening?

**Comment by kaiphat** [comment]
My dotfiles
https://github.com/kaiphat/dotfiles

**Comment by mbirghan** [comment]
@kaiphat You have set `splitright` to true which causes vsplits to be opened from the right. See https://github.com/kaiphat/dotfiles/blob/master/nvim/lua/options.lua#L40

**Comment by kaiphat** [comment]
Thank you! You are right, i don't remember about this option. But i think that plugin should have similar option.
