### ISSUE TITLE
Install size large due to gif

### ISSUE THREAD

**Issue by Benjscho** [FraserLee/ScratchPad#11]
The download and install size on disk is massive (85Mb) due to storing the Readme intro gif in the repository. The welcome gif is a really great intro to the plugin, but you can save 90% on download time and disk space if you host it in a different location or repo and point to it here. May also need to remove it from the git history since the git objects looks large too.

```
 $ du -h ./ScratchPad/ | sort -h | tail
16K     ./ScratchPad/lua
24K     ./ScratchPad/.git/logs/refs
28K     ./ScratchPad/.git/refs
32K     ./ScratchPad/.git/logs
64K     ./ScratchPad/.git/hooks
43M     ./ScratchPad/.git
43M     ./ScratchPad/.git/objects
43M     ./ScratchPad/.git/objects/pack
43M     ./ScratchPad/screenshots
85M     ./ScratchPad/
```

**Comment by FraserLee** [comment]
ah that totally slipped my mind, it really should be external to the repo. Good catch. 

Do you know if plugin managers will typically clone the whole repo with history, will they just download the current version? If the former, I'll find some way to purge it from the git history and possibly update the readme to historically reference the external link with some filter-branch hacks.

**Comment by FraserLee** [comment]
After looking into it a bit, it seems like they do the obvious thing and clone the whole thing. I've moved the files and changed the readme to reference a different repo, and deleted the files from history. Hopefully that should work alright!
