### ISSUE TITLE
Close nvim on start

### ISSUE THREAD

**Issue by kaiphat** [FraserLee/ScratchPad#2]
When i have two panes, one with code and second with scratch pad, i close pane with code, nvim is closed. It's ok.
But when i open nvim, without started screen, and press `<C-o>` nvim is closed immediately.

P.S.: My english is not very well, sorry)

Thank you!

**Comment by FraserLee** [comment]
I'm not 100% certain what you're describing- what is `<C-o>` supposed to do in that situation?

**Comment by FraserLee** [comment]
I can't seem to replicate the behaviour on my end. If you'd like to send me your vimrc (preferable a minimum failing copy) I could take a look to figure out what's going wrong :)

**Comment by kaiphat** [comment]
https://github.com/kaiphat/dotfiles

**Comment by kaiphat** [comment]
When i press `<C-o>` i open previously screen. In this case that screen is .scratchpad.

**Comment by mbirghan** [comment]
If the only window you have open is displaying scratchpad then scratchpad closes this window.
