### ISSUE TITLE
`let g:scratchpad_location = 'myfile'` in `~/.vimrc` does not work

### ISSUE THREAD

**Issue by beau-mind** [FraserLee/ScratchPad#3]
For this to work, the source code file `scratchpad.vim` needs to be changed as follows:

```
if !exists('g:scratchpad_location')
        let g:scratchpad_location = '~/.scratchpad'
endif
```

and so on for all the configuration variables.

**Comment by FraserLee** [comment]
Fixed by 0c87351e1413bfec47a223d577cc276f6892fb6a . Thanks for the report!
